# Generated by Django 6.0.8 on 2026-09-14 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_template_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(max_length=512)),
                ('language', models.CharField(max_length=16)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], max_length=32)),
                ('previous_category', models.CharField(blank=True, choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('IN_APPEAL', 'In appeal'), ('PENDING_DELETION', 'Pending deletion'), ('DELETED', 'Deleted'), ('LIMIT_EXCEEDED', 'Limit exceeded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=32)),
                ('rejected_reason', models.CharField(blank=True, max_length=255)),
                ('quality_score', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('UNKNOWN', 'Not yet rated')], default='UNKNOWN', max_length=16)),
                ('components', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('waba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='whatsapp.whatsappbusinessaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('meta_template_id', ''), _negated=True), fields=('meta_template_id',), name='message_templates_unique_meta_template_id'), models.UniqueConstraint(fields=('waba', 'name', 'language'), name='message_templates_unique_waba_name_language')],
            },
        ),
    ]
