# Generated by Django 6.0.8 on 2026-09-14 14:24

import apps.seller_alerts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('phone_e164', models.CharField(max_length=16)),
                ('wa_id', models.CharField(db_index=True, max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('opted_out', 'Opted out')], default='pending', max_length=16)),
                ('events', models.JSONField(blank=True, default=apps.seller_alerts.models.default_alert_events)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('verify', 'Verification'), ('new_order', 'New order'), ('needs_attention', 'Needs attention'), ('order_cancelled', 'Order cancelled'), ('reply', 'Command reply')], max_length=24)),
                ('to_wa_id', models.CharField(blank=True, max_length=15)),
                ('wamid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.workspace')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='seller_alerts.alertrecipient')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingSellerReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('awaiting_awb', 'Awaiting courier and AWB')], max_length=24)),
                ('prompt_wamid', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_replies', to='seller_alerts.alertrecipient')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['wa_id', 'status'], name='seller_alerts_rcpt_wa_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['workspace', 'status'], name='seller_alerts_rcpt_ws_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrecipient',
            constraint=models.UniqueConstraint(fields=('workspace', 'phone_e164'), name='seller_alerts_recipient_unique_phone'),
        ),
        migrations.AddIndex(
            model_name='alertmessage',
            index=models.Index(fields=['status', 'created_at'], name='seller_alerts_msg_status_idx'),
        ),
        migrations.AddIndex(
            model_name='alertmessage',
            index=models.Index(fields=['recipient', 'created_at'], name='seller_alerts_msg_rcpt_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingsellerreply',
            index=models.Index(fields=['recipient', 'expires_at'], name='seller_alerts_pending_idx'),
        ),
    ]
