# Generated by Django 6.0.8 on 2026-09-14 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertInboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wamid', models.CharField(max_length=128, unique=True)),
                ('from_wa_id', models.CharField(db_index=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField(blank=True)),
                ('reply_id', models.CharField(blank=True, max_length=256)),
                ('outcome', models.CharField(choices=[('handled', 'Handled'), ('ignored', 'Ignored (unknown or unverified sender)')], default='handled', max_length=16)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alertmessage',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='last_inbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
