# Generated by Django 6.0.8 on 2026-09-14 05:45

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waba_id', models.CharField(max_length=64, unique=True)),
                ('business_id', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('timezone_id', models.CharField(blank=True, max_length=16)),
                ('message_template_namespace', models.CharField(blank=True, max_length=128)),
                ('access_token', common.fields.EncryptedTextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('restricted', 'Restricted'), ('disabled', 'Disabled'), ('disconnected', 'Disconnected')], default='pending', max_length=16)),
                ('onboarding_status', models.CharField(choices=[('code_exchanged', 'Code exchanged'), ('subscribing', 'Subscribing to webhooks'), ('registering', 'Registering phone number'), ('completed', 'Completed'), ('failed', 'Failed')], default='code_exchanged', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'verbose_name': 'WhatsApp Business Account',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number_id', models.CharField(max_length=64, unique=True)),
                ('display_phone_number', models.CharField(max_length=32)),
                ('phone_e164', models.CharField(blank=True, max_length=20)),
                ('verified_name', models.CharField(blank=True, max_length=255)),
                ('name_status', models.CharField(blank=True, max_length=32)),
                ('quality_rating', models.CharField(choices=[('GREEN', 'High'), ('YELLOW', 'Medium'), ('RED', 'Low'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('messaging_limit_tier', models.CharField(blank=True, max_length=32)),
                ('throughput_level', models.CharField(blank=True, max_length=32)),
                ('platform_type', models.CharField(blank=True, max_length=32)),
                ('code_verification_status', models.CharField(blank=True, max_length=32)),
                ('meta_status', models.CharField(blank=True, max_length=32)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('failed', 'Failed'), ('deregistered', 'Deregistered')], default='pending', max_length=16)),
                ('is_coexistence', models.BooleanField(default=False)),
                ('pin', common.fields.EncryptedTextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
                ('waba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('workspace',), name='whatsapp_one_default_phone_per_workspace')],
            },
        ),
    ]
