/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Blacklist a refresh token. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Exchange email + password for an access/refresh token pair. */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Rotate a refresh token. The old refresh token is blacklisted. */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        get: operations["contacts_list"];
        put?: never;
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        post: operations["contacts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        get: operations["contacts_retrieve"];
        put?: never;
        post?: never;
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        delete: operations["contacts_destroy"];
        options?: never;
        head?: never;
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        patch: operations["contacts_partial_update"];
        trace?: never;
    };
    "/api/v1/contacts/{id}/consent-events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        get: operations["contacts_consent_events_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/opt-in/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        post: operations["contacts_opt_in_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/opt-out/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        post: operations["contacts_opt_out_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/bulk-tag/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Contacts of the header workspace. Consent changes only through opt-in/opt-out. */
        post: operations["contacts_bulk_tag_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/imports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CSV contact imports. Uploading starts a background import. */
        get: operations["contacts_imports_list"];
        put?: never;
        /** @description CSV contact imports. Uploading starts a background import. */
        post: operations["contacts_imports_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/imports/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CSV contact imports. Uploading starts a background import. */
        get: operations["contacts_imports_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Turn a unique-constraint race on save into 409 (serializers pre-check the common case). */
        get: operations["contacts_tags_list"];
        put?: never;
        /** @description Turn a unique-constraint race on save into 409 (serializers pre-check the common case). */
        post: operations["contacts_tags_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/tags/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Turn a unique-constraint race on save into 409 (serializers pre-check the common case). */
        get: operations["contacts_tags_retrieve"];
        put?: never;
        post?: never;
        /** @description Turn a unique-constraint race on save into 409 (serializers pre-check the common case). */
        delete: operations["contacts_tags_destroy"];
        options?: never;
        head?: never;
        /** @description Turn a unique-constraint race on save into 409 (serializers pre-check the common case). */
        patch: operations["contacts_tags_partial_update"];
        trace?: never;
    };
    "/api/v1/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description WhatsApp message templates of the header workspace.
         *
         *     Created as local drafts, then submitted to Meta for review. Drafts and rejected templates can
         *     be edited; everything else is read-only until Meta changes its status.
         */
        get: operations["templates_list"];
        put?: never;
        /**
         * @description WhatsApp message templates of the header workspace.
         *
         *     Created as local drafts, then submitted to Meta for review. Drafts and rejected templates can
         *     be edited; everything else is read-only until Meta changes its status.
         */
        post: operations["templates_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description WhatsApp message templates of the header workspace.
         *
         *     Created as local drafts, then submitted to Meta for review. Drafts and rejected templates can
         *     be edited; everything else is read-only until Meta changes its status.
         */
        get: operations["templates_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description WhatsApp message templates of the header workspace.
         *
         *     Created as local drafts, then submitted to Meta for review. Drafts and rejected templates can
         *     be edited; everything else is read-only until Meta changes its status.
         */
        delete: operations["templates_destroy"];
        options?: never;
        head?: never;
        /**
         * @description WhatsApp message templates of the header workspace.
         *
         *     Created as local drafts, then submitted to Meta for review. Drafts and rejected templates can
         *     be edited; everything else is read-only until Meta changes its status.
         */
        patch: operations["templates_partial_update"];
        trace?: never;
    };
    "/api/v1/templates/{id}/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Render the template with body (and header) variables. */
        post: operations["templates_preview_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send a draft or rejected template to Meta for review. */
        post: operations["templates_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/sync/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Queue a sync from Meta for one account, or every active account in the workspace. */
        post: operations["templates_sync_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Connected WhatsApp Business Accounts. Deleting one disconnects it. */
        get: operations["whatsapp_accounts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/accounts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Connected WhatsApp Business Accounts. Deleting one disconnects it. */
        get: operations["whatsapp_accounts_retrieve"];
        put?: never;
        post?: never;
        /** @description Connected WhatsApp Business Accounts. Deleting one disconnects it. */
        delete: operations["whatsapp_accounts_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/accounts/{id}/resync/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Connected WhatsApp Business Accounts. Deleting one disconnects it. */
        post: operations["whatsapp_accounts_resync_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/embedded-signup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Finish Embedded Signup with the code and ids from the frontend's session-info event. */
        post: operations["whatsapp_embedded_signup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/phone-numbers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compose with DRF mixins (ListModelMixin, ...) for partial CRUD. */
        get: operations["whatsapp_phone_numbers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/phone-numbers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compose with DRF mixins (ListModelMixin, ...) for partial CRUD. */
        get: operations["whatsapp_phone_numbers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/phone-numbers/{id}/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compose with DRF mixins (ListModelMixin, ...) for partial CRUD. */
        post: operations["whatsapp_phone_numbers_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/phone-numbers/{id}/retry-registration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compose with DRF mixins (ListModelMixin, ...) for partial CRUD. */
        post: operations["whatsapp_phone_numbers_retry_registration_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/phone-numbers/{id}/set-default/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compose with DRF mixins (ListModelMixin, ...) for partial CRUD. */
        post: operations["whatsapp_phone_numbers_set_default_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/signup-config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public Meta app settings the frontend needs to launch Embedded Signup. */
        get: operations["whatsapp_signup_config_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Workspaces the caller belongs to. Addressed by id in the URL, not the header. */
        get: operations["workspaces_list"];
        put?: never;
        /** @description Workspaces the caller belongs to. Addressed by id in the URL, not the header. */
        post: operations["workspaces_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Workspaces the caller belongs to. Addressed by id in the URL, not the header. */
        get: operations["workspaces_retrieve"];
        put?: never;
        post?: never;
        /** @description Workspaces the caller belongs to. Addressed by id in the URL, not the header. */
        delete: operations["workspaces_destroy"];
        options?: never;
        head?: never;
        /** @description Workspaces the caller belongs to. Addressed by id in the URL, not the header. */
        patch: operations["workspaces_partial_update"];
        trace?: never;
    };
    "/api/v1/workspaces/invitations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Open invitations for the header workspace. Deleting one revokes it. */
        get: operations["workspaces_invitations_list"];
        put?: never;
        /** @description Open invitations for the header workspace. Deleting one revokes it. */
        post: operations["workspaces_invitations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/invitations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Open invitations for the header workspace. Deleting one revokes it. */
        delete: operations["workspaces_invitations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/invitations/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaces_invitations_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Members of the header workspace. Anyone may leave; admins manage others. */
        get: operations["workspaces_members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/members/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Members of the header workspace. Anyone may leave; admins manage others. */
        get: operations["workspaces_members_retrieve"];
        put?: never;
        post?: never;
        /** @description Members of the header workspace. Anyone may leave; admins manage others. */
        delete: operations["workspaces_members_destroy"];
        options?: never;
        head?: never;
        /** @description Members of the header workspace. Anyone may leave; admins manage others. */
        patch: operations["workspaces_members_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptedInvitation: {
            workspace: components["schemas"]["WorkspaceSummary"];
            role: components["schemas"]["RoleEnum"];
        };
        BulkTagRequest: {
            contact_ids: string[];
            add_tag_ids?: string[];
            remove_tag_ids?: string[];
        };
        BulkTagResult: {
            contact_count: number;
            /** @description Tag links created. */
            added: number;
            /** @description Tag links removed. */
            removed: number;
        };
        /**
         * @description * `opt_in` - Opt in
         *     * `opt_out` - Opt out
         * @enum {string}
         */
        ConsentActionEnum: "opt_in" | "opt_out";
        ConsentEvent: {
            /** Format: uuid */
            readonly id: string;
            readonly purpose: components["schemas"]["ConsentPurposeEnum"];
            readonly action: components["schemas"]["ConsentActionEnum"];
            readonly source: components["schemas"]["ConsentSourceEnum"];
            readonly evidence: string;
            /** Format: uuid */
            readonly actor: string | null;
            readonly wamid: string;
            /** Format: date-time */
            readonly occurred_at: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `marketing` - Marketing
         * @enum {string}
         */
        ConsentPurposeEnum: "marketing";
        ConsentRequestRequest: {
            /** @default manual */
            source: components["schemas"]["ConsentRequestSourceEnum"];
            evidence?: string;
        };
        /**
         * @description * `manual` - Manual
         *     * `api` - API
         * @enum {string}
         */
        ConsentRequestSourceEnum: "manual" | "api";
        /**
         * @description * `manual` - Manual
         *     * `import` - Import
         *     * `api` - API
         *     * `whatsapp_keyword` - WhatsApp keyword
         *     * `meta_marketing_optout` - Meta marketing opt-out
         * @enum {string}
         */
        ConsentSourceEnum: "manual" | "import" | "api" | "whatsapp_keyword" | "meta_marketing_optout";
        Contact: {
            /** Format: uuid */
            readonly id: string;
            /** @description Any common format; Indian local numbers are accepted. Stored as E.164. */
            phone_e164: string;
            readonly wa_id: string;
            name?: string;
            email?: string;
            attributes?: {
                [key: string]: unknown;
            };
            tags?: string[];
            readonly marketing_opt_in_status: components["schemas"]["ContactOptInStatusEnum"];
            /** Format: date-time */
            readonly opted_in_at: string | null;
            /** Format: date-time */
            readonly opted_out_at: string | null;
            readonly opt_in_source: string;
            /** Format: date-time */
            readonly last_inbound_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ContactImport: {
            /** Format: uuid */
            readonly id: string;
            readonly file_name: string;
            readonly status: components["schemas"]["ContactImportStatusEnum"];
            readonly total_rows: number;
            readonly created_count: number;
            readonly updated_count: number;
            readonly skipped_count: number;
            readonly error_count: number;
            readonly errors: components["schemas"]["ImportRowError"][];
            readonly mark_opted_in: boolean;
            readonly consent_attested: boolean;
            readonly opt_in_source: string;
            readonly tags: string[];
            /** Format: uuid */
            readonly created_by: string | null;
            /** Format: date-time */
            readonly started_at: string | null;
            /** Format: date-time */
            readonly finished_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        ContactImportCreateRequest: {
            /**
             * Format: binary
             * @description UTF-8 CSV with a phone column.
             */
            file: string;
            mark_opted_in?: boolean;
            consent_attested?: boolean;
            /** @description Where these contacts opted in, e.g. 'Checkout form on example.in'. */
            opt_in_source?: string;
            tag_ids?: string[];
        };
        /**
         * @description * `queued` - Queued
         *     * `processing` - Processing
         *     * `completed` - Completed
         *     * `failed` - Failed
         * @enum {string}
         */
        ContactImportStatusEnum: "queued" | "processing" | "completed" | "failed";
        /**
         * @description * `unknown` - Unknown
         *     * `opted_in` - Opted in
         *     * `opted_out` - Opted out
         * @enum {string}
         */
        ContactOptInStatusEnum: "unknown" | "opted_in" | "opted_out";
        ContactRequest: {
            /** @description Any common format; Indian local numbers are accepted. Stored as E.164. */
            phone_e164: string;
            name?: string;
            email?: string;
            attributes?: {
                [key: string]: unknown;
            };
            tags?: string[];
        };
        EmbeddedSignupRequest: {
            code: string;
            waba_id: string;
            phone_number_id?: string;
            business_id?: string;
            /** @default false */
            coexistence: boolean;
        };
        ImportRowError: {
            /** @description 1-based CSV line; null if global. */
            row: number | null;
            error: string;
        };
        Invitation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            role?: components["schemas"]["RoleEnum"];
            readonly status: components["schemas"]["InvitationStatusEnum"];
            readonly invited_by: components["schemas"]["MemberUser"];
            /** Format: date-time */
            readonly expires_at: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        InvitationAcceptRequest: {
            token: string;
        };
        InvitationRequest: {
            /** Format: email */
            email: string;
            role?: components["schemas"]["RoleEnum"];
        };
        /**
         * @description * `pending` - Pending
         *     * `accepted` - Accepted
         *     * `revoked` - Revoked
         *     * `expired` - Expired
         * @enum {string}
         */
        InvitationStatusEnum: "pending" | "accepted" | "revoked" | "expired";
        Me: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            full_name?: string;
            /** Format: date-time */
            readonly date_joined: string;
            /** Format: date-time */
            readonly email_verified_at: string | null;
            readonly memberships: components["schemas"]["WorkspaceMembershipSummary"][];
        };
        MemberUser: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Email address
             * Format: email
             */
            email: string;
            full_name?: string;
        };
        MemberUserRequest: {
            /**
             * Email address
             * Format: email
             */
            email: string;
            full_name?: string;
        };
        Membership: {
            /** Format: uuid */
            readonly id: string;
            readonly user: components["schemas"]["MemberUser"];
            role?: components["schemas"]["RoleEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        MessageTemplate: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            waba: string;
            readonly meta_template_id: string;
            name: string;
            language: string;
            category: components["schemas"]["MessageTemplateCategoryEnum"];
            readonly previous_category: components["schemas"]["MessageTemplateCategoryEnum"];
            readonly status: components["schemas"]["MessageTemplateStatusEnum"];
            readonly rejected_reason: string;
            readonly quality_score: components["schemas"]["TemplateQualityScoreEnum"];
            /** @description Template components in Meta's format (HEADER, BODY, FOOTER, BUTTONS). */
            components: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            readonly submitted_at: string | null;
            /** Format: date-time */
            readonly last_synced_at: string | null;
            /** Format: uuid */
            readonly created_by: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `MARKETING` - Marketing
         *     * `UTILITY` - Utility
         *     * `AUTHENTICATION` - Authentication
         * @enum {string}
         */
        MessageTemplateCategoryEnum: "MARKETING" | "UTILITY" | "AUTHENTICATION";
        MessageTemplateRequest: {
            /** Format: uuid */
            waba: string;
            name: string;
            language: string;
            category: components["schemas"]["MessageTemplateCategoryEnum"];
            /** @description Template components in Meta's format (HEADER, BODY, FOOTER, BUTTONS). */
            components: {
                [key: string]: unknown;
            }[];
        };
        /**
         * @description * `DRAFT` - Draft
         *     * `PENDING` - Pending review
         *     * `APPROVED` - Approved
         *     * `REJECTED` - Rejected
         *     * `PAUSED` - Paused
         *     * `DISABLED` - Disabled
         *     * `IN_APPEAL` - In appeal
         *     * `PENDING_DELETION` - Pending deletion
         *     * `DELETED` - Deleted
         *     * `LIMIT_EXCEEDED` - Limit exceeded
         *     * `ARCHIVED` - Archived
         * @enum {string}
         */
        MessageTemplateStatusEnum: "DRAFT" | "PENDING" | "APPROVED" | "REJECTED" | "PAUSED" | "DISABLED" | "IN_APPEAL" | "PENDING_DELETION" | "DELETED" | "LIMIT_EXCEEDED" | "ARCHIVED";
        OptInRequestRequest: {
            /** @default manual */
            source: components["schemas"]["ConsentRequestSourceEnum"];
            /** @description How and when the customer agreed to receive marketing messages. Required. */
            evidence?: string;
        };
        PaginatedConsentEventList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["ConsentEvent"][];
        };
        PaginatedContactImportList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["ContactImport"][];
        };
        PaginatedContactList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Contact"][];
        };
        PaginatedInvitationList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Invitation"][];
        };
        PaginatedMembershipList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Membership"][];
        };
        PaginatedMessageTemplateList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["MessageTemplate"][];
        };
        PaginatedPhoneNumberList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["PhoneNumber"][];
        };
        PaginatedTagList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Tag"][];
        };
        PaginatedWhatsAppBusinessAccountList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["WhatsAppBusinessAccount"][];
        };
        PaginatedWorkspaceList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Workspace"][];
        };
        PasswordChangeRequest: {
            current_password: string;
            new_password: string;
        };
        PatchedContactRequest: {
            /** @description Any common format; Indian local numbers are accepted. Stored as E.164. */
            phone_e164?: string;
            name?: string;
            email?: string;
            attributes?: {
                [key: string]: unknown;
            };
            tags?: string[];
        };
        PatchedMeRequest: {
            full_name?: string;
        };
        PatchedMembershipRequest: {
            role?: components["schemas"]["RoleEnum"];
        };
        PatchedMessageTemplateRequest: {
            /** Format: uuid */
            waba?: string;
            name?: string;
            language?: string;
            category?: components["schemas"]["MessageTemplateCategoryEnum"];
            /** @description Template components in Meta's format (HEADER, BODY, FOOTER, BUTTONS). */
            components?: {
                [key: string]: unknown;
            }[];
        };
        PatchedTagRequest: {
            name?: string;
            color?: string;
        };
        PatchedWorkspaceRequest: {
            name?: string;
            time_zone?: string;
        };
        /** @description Never exposes the registration PIN. */
        PhoneNumber: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly waba: string;
            readonly phone_number_id: string;
            readonly display_phone_number: string;
            readonly phone_e164: string;
            readonly verified_name: string;
            readonly name_status: string;
            readonly quality_rating: components["schemas"]["PhoneQualityRatingEnum"];
            readonly messaging_limit_tier: string;
            readonly throughput_level: string;
            readonly platform_type: string;
            readonly code_verification_status: string;
            readonly meta_status: string;
            readonly registration_status: components["schemas"]["PhoneRegistrationStatusEnum"];
            readonly is_coexistence: boolean;
            readonly is_default: boolean;
            /** Format: date-time */
            readonly last_synced_at: string | null;
            readonly last_error: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `GREEN` - High
         *     * `YELLOW` - Medium
         *     * `RED` - Low
         *     * `UNKNOWN` - Unknown
         * @enum {string}
         */
        PhoneQualityRatingEnum: "GREEN" | "YELLOW" | "RED" | "UNKNOWN";
        /**
         * @description * `pending` - Pending
         *     * `registered` - Registered
         *     * `failed` - Failed
         *     * `deregistered` - Deregistered
         * @enum {string}
         */
        PhoneRegistrationStatusEnum: "pending" | "registered" | "failed" | "deregistered";
        Preview: {
            header: components["schemas"]["PreviewHeader"] | null;
            body: string;
            footer: string | null;
            buttons: components["schemas"]["PreviewButton"][];
        };
        PreviewButton: {
            type: string;
            text: string;
            url?: string;
            phone_number?: string;
        };
        PreviewHeader: {
            format: string;
            text: string | null;
        };
        PreviewRequestRequest: {
            variables?: string[];
            header_variables?: string[];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            full_name?: string;
        };
        RegisterResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["TokenPair"];
        };
        /**
         * @description * `owner` - Owner
         *     * `admin` - Admin
         *     * `agent` - Agent
         *     * `viewer` - Viewer
         * @enum {string}
         */
        RoleEnum: "owner" | "admin" | "agent" | "viewer";
        SignupConfig: {
            app_id: string;
            config_id: string;
            graph_api_version: string;
        };
        SyncQueued: {
            queued: string[];
        };
        SyncRequestRequest: {
            /** @description Our WABA id (UUID) or Meta's WABA id. Omit to sync every active account. */
            waba_id?: string;
        };
        Tag: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            color?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        TagRequest: {
            name: string;
            color?: string;
        };
        /**
         * @description * `GREEN` - Green
         *     * `YELLOW` - Yellow
         *     * `RED` - Red
         *     * `UNKNOWN` - Not yet rated
         * @enum {string}
         */
        TemplateQualityScoreEnum: "GREEN" | "YELLOW" | "RED" | "UNKNOWN";
        TokenBlacklistRequest: {
            refresh: string;
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            email: string;
            password: string;
        };
        TokenPair: {
            access: string;
            refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            full_name?: string;
            /** Format: date-time */
            readonly date_joined: string;
            /** Format: date-time */
            readonly email_verified_at: string | null;
        };
        /**
         * @description * `code_exchanged` - Code exchanged
         *     * `subscribing` - Subscribing to webhooks
         *     * `registering` - Registering phone number
         *     * `completed` - Completed
         *     * `failed` - Failed
         * @enum {string}
         */
        WabaOnboardingStatusEnum: "code_exchanged" | "subscribing" | "registering" | "completed" | "failed";
        /**
         * @description * `pending` - Pending
         *     * `active` - Active
         *     * `restricted` - Restricted
         *     * `disabled` - Disabled
         *     * `disconnected` - Disconnected
         * @enum {string}
         */
        WabaStatusEnum: "pending" | "active" | "restricted" | "disabled" | "disconnected";
        /** @description Never exposes the access token. */
        WhatsAppBusinessAccount: {
            /** Format: uuid */
            readonly id: string;
            readonly waba_id: string;
            readonly business_id: string;
            readonly name: string;
            readonly currency: string;
            readonly timezone_id: string;
            readonly message_template_namespace: string;
            readonly status: components["schemas"]["WabaStatusEnum"];
            readonly onboarding_status: components["schemas"]["WabaOnboardingStatusEnum"];
            readonly last_error: string;
            /** Format: date-time */
            readonly subscribed_at: string | null;
            /** Format: date-time */
            readonly token_expires_at: string | null;
            /** Format: uuid */
            readonly connected_by: string | null;
            readonly phone_numbers: components["schemas"]["PhoneNumber"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Workspace: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            readonly slug: string;
            time_zone?: string;
            readonly my_role: components["schemas"]["RoleEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        WorkspaceMembershipSummary: {
            /** Format: uuid */
            workspace_id: string;
            workspace_name: string;
            workspace_slug: string;
            role: components["schemas"]["RoleEnum"];
        };
        WorkspaceRequest: {
            name: string;
            time_zone?: string;
        };
        WorkspaceSummary: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBlacklistRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenBlacklistRequest"];
                "multipart/form-data": components["schemas"]["TokenBlacklistRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMeRequest"];
                "multipart/form-data": components["schemas"]["PatchedMeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    contacts_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /**
                 * @description * `unknown` - Unknown
                 *     * `opted_in` - Opted in
                 *     * `opted_out` - Opted out
                 */
                marketing_opt_in_status?: "opted_in" | "opted_out" | "unknown";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /** @description Tag id */
                tag?: string;
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedContactList"];
                };
            };
        };
    };
    contacts_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ContactRequest"];
                "multipart/form-data": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
        };
    };
    contacts_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
        };
    };
    contacts_destroy: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    contacts_partial_update: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedContactRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedContactRequest"];
                "multipart/form-data": components["schemas"]["PatchedContactRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
        };
    };
    contacts_consent_events_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConsentEventList"];
                };
            };
        };
    };
    contacts_opt_in_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OptInRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OptInRequestRequest"];
                "multipart/form-data": components["schemas"]["OptInRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
        };
    };
    contacts_opt_out_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConsentRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ConsentRequestRequest"];
                "multipart/form-data": components["schemas"]["ConsentRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
        };
    };
    contacts_bulk_tag_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkTagRequest"];
                "multipart/form-data": components["schemas"]["BulkTagRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkTagResult"];
                };
            };
        };
    };
    contacts_imports_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedContactImportList"];
                };
            };
        };
    };
    contacts_imports_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ContactImportCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactImport"];
                };
            };
        };
    };
    contacts_imports_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactImport"];
                };
            };
        };
    };
    contacts_tags_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTagList"];
                };
            };
        };
    };
    contacts_tags_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TagRequest"];
                "multipart/form-data": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    contacts_tags_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    contacts_tags_destroy: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    contacts_tags_partial_update: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTagRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTagRequest"];
                "multipart/form-data": components["schemas"]["PatchedTagRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    templates_list: {
        parameters: {
            query?: {
                /**
                 * @description * `MARKETING` - Marketing
                 *     * `UTILITY` - Utility
                 *     * `AUTHENTICATION` - Authentication
                 */
                category?: "AUTHENTICATION" | "MARKETING" | "UTILITY";
                /** @description The pagination cursor value. */
                cursor?: string;
                language?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `DRAFT` - Draft
                 *     * `PENDING` - Pending review
                 *     * `APPROVED` - Approved
                 *     * `REJECTED` - Rejected
                 *     * `PAUSED` - Paused
                 *     * `DISABLED` - Disabled
                 *     * `IN_APPEAL` - In appeal
                 *     * `PENDING_DELETION` - Pending deletion
                 *     * `DELETED` - Deleted
                 *     * `LIMIT_EXCEEDED` - Limit exceeded
                 *     * `ARCHIVED` - Archived
                 */
                status?: "APPROVED" | "ARCHIVED" | "DELETED" | "DISABLED" | "DRAFT" | "IN_APPEAL" | "LIMIT_EXCEEDED" | "PAUSED" | "PENDING" | "PENDING_DELETION" | "REJECTED";
                waba?: string;
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessageTemplateList"];
                };
            };
        };
    };
    templates_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageTemplateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MessageTemplateRequest"];
                "multipart/form-data": components["schemas"]["MessageTemplateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplate"];
                };
            };
        };
    };
    templates_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplate"];
                };
            };
        };
    };
    templates_destroy: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    templates_partial_update: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMessageTemplateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMessageTemplateRequest"];
                "multipart/form-data": components["schemas"]["PatchedMessageTemplateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplate"];
                };
            };
        };
    };
    templates_preview_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PreviewRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PreviewRequestRequest"];
                "multipart/form-data": components["schemas"]["PreviewRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
        };
    };
    templates_submit_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplate"];
                };
            };
        };
    };
    templates_sync_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SyncRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SyncRequestRequest"];
                "multipart/form-data": components["schemas"]["SyncRequestRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncQueued"];
                };
            };
        };
    };
    whatsapp_accounts_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /**
                 * @description * `code_exchanged` - Code exchanged
                 *     * `subscribing` - Subscribing to webhooks
                 *     * `registering` - Registering phone number
                 *     * `completed` - Completed
                 *     * `failed` - Failed
                 */
                onboarding_status?: "code_exchanged" | "completed" | "failed" | "registering" | "subscribing";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `pending` - Pending
                 *     * `active` - Active
                 *     * `restricted` - Restricted
                 *     * `disabled` - Disabled
                 *     * `disconnected` - Disconnected
                 */
                status?: "active" | "disabled" | "disconnected" | "pending" | "restricted";
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWhatsAppBusinessAccountList"];
                };
            };
        };
    };
    whatsapp_accounts_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppBusinessAccount"];
                };
            };
        };
    };
    whatsapp_accounts_destroy: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    whatsapp_accounts_resync_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppBusinessAccount"];
                };
            };
        };
    };
    whatsapp_embedded_signup_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbeddedSignupRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmbeddedSignupRequest"];
                "multipart/form-data": components["schemas"]["EmbeddedSignupRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppBusinessAccount"];
                };
            };
        };
    };
    whatsapp_phone_numbers_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                is_default?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `GREEN` - High
                 *     * `YELLOW` - Medium
                 *     * `RED` - Low
                 *     * `UNKNOWN` - Unknown
                 */
                quality_rating?: "GREEN" | "RED" | "UNKNOWN" | "YELLOW";
                /**
                 * @description * `pending` - Pending
                 *     * `registered` - Registered
                 *     * `failed` - Failed
                 *     * `deregistered` - Deregistered
                 */
                registration_status?: "deregistered" | "failed" | "pending" | "registered";
                /** @description A search term. */
                search?: string;
                waba?: string;
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPhoneNumberList"];
                };
            };
        };
    };
    whatsapp_phone_numbers_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"];
                };
            };
        };
    };
    whatsapp_phone_numbers_refresh_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"];
                };
            };
        };
    };
    whatsapp_phone_numbers_retry_registration_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"];
                };
            };
        };
    };
    whatsapp_phone_numbers_set_default_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"];
                };
            };
        };
    };
    whatsapp_signup_config_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupConfig"];
                };
            };
        };
    };
    workspaces_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkspaceList"];
                };
            };
        };
    };
    workspaces_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkspaceRequest"];
                "multipart/form-data": components["schemas"]["WorkspaceRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaces_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaces_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWorkspaceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWorkspaceRequest"];
                "multipart/form-data": components["schemas"]["PatchedWorkspaceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaces_invitations_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInvitationList"];
                };
            };
        };
    };
    workspaces_invitations_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["InvitationRequest"];
                "multipart/form-data": components["schemas"]["InvitationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
        };
    };
    workspaces_invitations_destroy: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_invitations_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["InvitationAcceptRequest"];
                "multipart/form-data": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedInvitation"];
                };
            };
        };
    };
    workspaces_members_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `owner` - Owner
                 *     * `admin` - Admin
                 *     * `agent` - Agent
                 *     * `viewer` - Viewer
                 */
                role?: "admin" | "agent" | "owner" | "viewer";
                /** @description A search term. */
                search?: string;
            };
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembershipList"];
                };
            };
        };
    };
    workspaces_members_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
        };
    };
    workspaces_members_destroy: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_members_partial_update: {
        parameters: {
            query?: never;
            header: {
                /** @description Workspace to act in. The caller must be a member. */
                "X-Workspace-ID": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMembershipRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMembershipRequest"];
                "multipart/form-data": components["schemas"]["PatchedMembershipRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
        };
    };
}
