# Generated by Django 6.0.8 on 2026-09-14 14:24

import apps.orders.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
        ('inbox', '0001_initial'),
        ('message_templates', '0001_initial'),
        ('tenants', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCounter',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order_counter', serialize=False, to='tenants.workspace')),
                ('last_value', models.PositiveIntegerField(default=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_confirmation', 'Awaiting confirmation'), ('awaiting_address', 'Awaiting address'), ('awaiting_payment_method', 'Awaiting payment method'), ('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('needs_attention', 'Needs attention')], default='draft', max_length=24)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('cod_pending', 'COD pending'), ('cod_collected', 'COD collected'), ('refunded_manual', 'Refunded manually')], default='unpaid', max_length=16)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online'), ('cod', 'Cash on delivery')], max_length=8)),
                ('source', models.CharField(choices=[('bot', 'Bot'), ('native_cart', 'Native cart')], default='bot', max_length=16)),
                ('source_wamid', models.CharField(blank=True, max_length=128)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('subtotal_paise', models.PositiveIntegerField(default=0)),
                ('shipping_paise', models.PositiveIntegerField(default=0)),
                ('cod_fee_paise', models.PositiveIntegerField(default=0)),
                ('total_paise', models.PositiveIntegerField(default=0)),
                ('quoted_total_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('address', models.JSONField(blank=True, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('awb_number', models.CharField(blank=True, max_length=64)),
                ('tracking_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('stock_reserved', models.BooleanField(default=False)),
                ('checkout_attempt', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cod_collected_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.conversation')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whatsapp.phonenumber')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('price_changed', 'Price changed'), ('address_received', 'Address received'), ('payment_link_created', 'Payment link created'), ('payment_received', 'Payment received'), ('payment_link_expired', 'Payment link expired'), ('cod_collected', 'COD collected'), ('refunded_manual', 'Refunded manually'), ('stock_released', 'Stock released'), ('notification_sent', 'Notification sent'), ('notification_failed', 'Notification failed'), ('note', 'Note')], max_length=24)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('actor', models.CharField(choices=[('buyer', 'Buyer'), ('dashboard', 'Dashboard'), ('seller_whatsapp', 'Seller on WhatsApp'), ('system', 'System')], default='system', max_length=16)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.message')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('unit_price_paise', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('line_total_paise', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopperAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('meta_saved_address_id', models.CharField(blank=True, max_length=128)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'verbose_name_plural': 'shopper addresses',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('shop_mode', models.CharField(choices=[('bot', 'Bot'), ('native_catalog', 'Native catalog')], default='bot', max_length=16)),
                ('store_name', models.CharField(blank=True, max_length=60)),
                ('welcome_message', models.TextField(blank=True, max_length=1024)),
                ('menu_keywords', models.JSONField(blank=True, default=apps.orders.models.default_menu_keywords)),
                ('order_prefix', models.CharField(default='UPC', max_length=5, validators=[django.core.validators.RegexValidator('^[A-Z]{2,5}$', 'Use 2-5 capital letters.')])),
                ('min_order_paise', models.PositiveIntegerField(default=0)),
                ('shipping_fee_paise', models.PositiveIntegerField(default=0)),
                ('free_shipping_above_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('cod_enabled', models.BooleanField(default=False)),
                ('cod_fee_paise', models.PositiveIntegerField(default=0)),
                ('cod_max_order_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('serviceable_pincodes', models.JSONField(blank=True, default=list)),
                ('support_message', models.TextField(blank=True, max_length=1024)),
                ('powered_by_footer', models.BooleanField(default=True)),
                ('cancelled_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message_templates.messagetemplate')),
                ('confirmed_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message_templates.messagetemplate')),
                ('delivered_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message_templates.messagetemplate')),
                ('packed_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message_templates.messagetemplate')),
                ('payment_reminder_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message_templates.messagetemplate')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.phonenumber')),
                ('shipped_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message_templates.messagetemplate')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to='tenants.workspace')),
            ],
            options={
                'verbose_name': 'store settings',
                'verbose_name_plural': 'store settings',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='orders_ws_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['workspace', 'created_at'], name='orders_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['workspace', 'payment_status'], name='orders_ws_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['workspace', 'payment_method'], name='orders_ws_pay_method_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['workspace', 'contact', 'created_at'], name='orders_ws_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='orders_status_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('workspace', 'number'), name='orders_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('source_wamid', ''), _negated=True), fields=('workspace', 'source_wamid'), name='orders_unique_source_wamid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'awaiting_confirmation', 'awaiting_address', 'awaiting_payment_method', 'pending_payment'))), fields=('workspace', 'contact', 'phone_number'), name='orders_one_active_checkout'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'created_at'], name='orders_event_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopperaddress',
            constraint=models.UniqueConstraint(fields=('workspace', 'contact'), name='orders_shopper_address_unique_contact'),
        ),
    ]
