# Generated by Django 6.0.8 on 2026-09-14 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbox', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('awaiting_quantity', 'Awaiting quantity'), ('awaiting_text', 'Awaiting text')], default='idle', max_length=24)),
                ('cart', models.JSONField(blank=True, default=list)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_session', to='inbox.conversation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['expires_at'], name='shop_session_expires_idx')],
            },
        ),
    ]
