# Generated by Django 6.0.8 on 2026-09-14 14:24

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(blank=True, max_length=72)),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('position', 'name'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_id', models.CharField(db_index=True, max_length=64)),
                ('catalog_name', models.CharField(blank=True, max_length=255)),
                ('business_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('permissions_missing', 'Permissions missing'), ('error', 'Error')], default='connected', max_length=24)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('waba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_catalog', to='whatsapp.whatsappbusinessaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogSyncBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('retailer_ids', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
                ('meta_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_batches', to='catalog.metacatalog')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaCatalogPhoneSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cart_enabled', models.BooleanField(default=False)),
                ('is_catalog_visible', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('meta_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_settings', to='catalog.metacatalog')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_setting', to='whatsapp.phonenumber')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]{1,100}$', 'Use 1-100 letters, digits, underscores or hyphens.')])),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price_paise', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('sale_price_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock')], default='in_stock', max_length=16)),
                ('stock_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('max_qty_per_order', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, max_length=255, upload_to=apps.catalog.models.product_image_path)),
                ('meta_sync_status', models.CharField(choices=[('not_synced', 'Not synced'), ('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='not_synced', max_length=16)),
                ('meta_review_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('outdated', 'Outdated')], default='none', max_length=16)),
                ('meta_rejection_reasons', models.JSONField(blank=True, default=list)),
                ('meta_product_id', models.CharField(blank=True, max_length=64)),
                ('meta_synced_at', models.DateTimeField(blank=True, null=True)),
                ('meta_sync_error', models.TextField(blank=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.collection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('position', 'name'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['workspace', 'position'], name='catalog_coll_ws_position_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='catalog_collection_unique_name_ci'),
        ),
        migrations.AddIndex(
            model_name='metacatalog',
            index=models.Index(fields=['workspace', 'status'], name='catalog_meta_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogsyncbatch',
            index=models.Index(fields=['status', 'created_at'], name='catalog_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'position', 'name'], name='catalog_prod_ws_position_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'collection'], name='catalog_prod_ws_coll_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'is_active', 'availability'], name='catalog_prod_ws_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'meta_review_status'], name='catalog_prod_ws_review_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'meta_sync_status'], name='catalog_prod_ws_sync_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('workspace', 'sku'), name='catalog_product_unique_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price_paise__gte', 100)), name='catalog_product_min_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price_paise__isnull', True), ('sale_price_paise__lt', models.F('price_paise')), _connector='OR'), name='catalog_product_sale_below_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('max_qty_per_order__gte', 1), ('max_qty_per_order__lte', 99)), name='catalog_product_max_qty_range'),
        ),
    ]
