# Generated by Django 6.0.8 on 2026-09-16 14:42

import apps.catalog.models
import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, max_length=255, storage=common.storage.public_media_storage, upload_to=apps.catalog.models.product_image_path),
        ),
    ]
