# Generated by Django 6.0.8 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive'), ('button', 'Button'), ('reaction', 'Reaction'), ('template', 'Template'), ('order', 'Order'), ('unsupported', 'Unsupported')], default='text', max_length=16),
        ),
    ]
