# Generated by Django 6.0.8 on 2026-09-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_message_type_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('inbox', 'Inbox'), ('campaign', 'Campaign'), ('automation', 'Automation'), ('api', 'API'), ('commerce', 'Commerce')], max_length=16),
        ),
    ]
