# Generated by Django 6.0.8 on 2026-09-14 14:24

import apps.payments.models
import common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay')], default='razorpay', max_length=16)),
                ('key_id', models.CharField(blank=True, max_length=64)),
                ('key_secret', common.fields.EncryptedTextField(blank=True)),
                ('webhook_secret', common.fields.EncryptedTextField(blank=True)),
                ('webhook_token', models.CharField(default=apps.payments.models.new_webhook_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('not_configured', 'Not configured'), ('unverified', 'Unverified'), ('verified', 'Verified'), ('invalid', 'Invalid')], default='not_configured', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay')], default='razorpay', max_length=16)),
                ('provider_link_id', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(max_length=40)),
                ('short_url', models.URLField(blank=True, max_length=255)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('created', 'Created'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='creating', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='orders.order')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', 'status'], name='payments_link_ws_status_idx'), models.Index(fields=['order', 'created_at'], name='payments_link_order_idx'), models.Index(fields=['provider_link_id'], name='payments_link_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'reference_id'), name='payments_link_unique_reference')],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('workspace', 'event_id'), name='payments_webhook_unique_event')],
            },
        ),
    ]
