# Generated by Django 6.0.8 on 2026-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='mode',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('live', 'Live')], max_length=8),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='next_poll_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='poll_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='key_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree')], default='razorpay', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree')], default='razorpay', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='provider_link_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['status', 'next_poll_at'], name='payments_link_poll_idx'),
        ),
    ]
